# Generated by Django 5.2.5 on 2025-08-21 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="user",
        ),
    ]
