# Generated by Django 5.2.5 on 2025-08-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dave", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="banner",
            field=models.ImageField(blank=True, default="fallback.png", upload_to=""),
        ),
    ]
