# Generated by Django 5.2.4 on 2025-08-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("print", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="database_model",
            name="joined_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="database_model",
            name="phone",
            field=models.IntegerField(null=True),
        ),
    ]
